import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const satoshiSans = localFont({
  src: "./font/Satoshi-Variable.ttf",
  variable: "--font-geist-sans",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiSans.className} antialiased`}>{children}</body>
    </html>
  );
}
